# Generated by Django 3.1.7 on 2021-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210330_0044'),
        ('profiles', '0002_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='products.Product'),
        ),
    ]
