# Generated by Django 3.1.7 on 2021-03-30 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeproducts',
            name='like',
        ),
        migrations.AddField(
            model_name='likeproducts',
            name='likes',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
