# Generated by Django 3.1.7 on 2021-03-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ratingproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingproducts',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
